### ISSUE TITLE
Trying with a fresh install of Python 2.7 fails..(?)

### ISSUE THREAD

**Issue by elliotwoods** [Falicon/Python-Hackpad-API#13]
```
e:\dev\Python-Hackpad-API>python setup.py install
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing C:\Python27\Lib\site-packages\python_hackpad_api-beta-py2.7.egg-info
Writing C:\Python27\Lib\site-packages\python_hackpad_api-beta-py2.7.egg-info

e:\dev\Python-Hackpad-API>cd example

e:\dev\Python-Hackpad-API\example>python example1.py
Traceback (most recent call last):
  File "example1.py", line 2, in <module>
    from hackpad_api.hackpad import Hackpad
  File "C:\Python27\lib\site-packages\hackpad_api\hackpad.py", line 6, in <module>
    import requests
ImportError: No module named requests

e:\dev\Python-Hackpad-API\example>
```

I admit i'm entirely inexperienced with python so i might be missing something really obvious here.

(Windows 10 x64)

**Comment by elliotwoods** [comment]
ok, using `easy_install .` in the downloaded folder works.
